### ISSUE TITLE
UTF8 character confusions

### ISSUE THREAD

**Issue by rbjones** [RobArthan/pp#7]
On the utf8 branch it is now possible to introduce arbitrary unicode characters without ceremony or documentation.  This creates risk of equivocation, since some of the glyphs are very similar.  Most users will not have a problem with this and will not use two distinct but indistinguishable characters, but some may think that the possibilities threaten the integrity of formal verification.

Should we give the option of not allowing characters not mentioned in a keyword file?

**Comment by RobArthan** [comment]
That sounds like a good idea to me if it's not too much trouble. The gamut of symbols that are now available makes accidental Pollack inconsistency a bit more of a concern.

**Comment by rbjones** [comment]
Probably the keyword file is the wrong place for a definitive statement of which characters are to be accepted, since it does not directly influence which characters are accepted by ProofPower.
In fact, prior to my putting a by-pass in characters not known to ProofPower (through the appropriate procedure call were not accepted.  So I think a better way to roll back that liberalisation might be to control that feature with a ProofPower flag.   However, before making that small change we need to consider whether that would suffice for most rigorous customers.
Alongside this it may be worth considering whether the present rather loose connection between what is recorded in the keyword files and the character set known to ProofPower is OK.

**Comment by RobArthan** [comment]
I think having this as an option when documents are typeset is useful to avoid accidental errors, particularly when using lualatex or similar to render Unicode glyphs directly rather than via LaTeX macros. My take on Pollack consistency within a theory database has always been that if it is a concern, then programmatic investigation of the use of names in the database is the best way to give extra confidence. The link between the keyword files and the character set installed in the ProofPower database is a separate issue (and one I'd like to defer until we take the next big step and convert the ML code to use Unicode strings for object language identifiers).

**Comment by rbjones** [comment]
OK, so you would like sieve to baulk at unicode code points not in the keyword files.
How serious should that be?  Print warning and omit the character?
Can we make this optional?  Controlled by command line flag and/or environment (default on)?

**Comment by RobArthan** [comment]
I think it would be OK to give a warning and output the character and I don't see any reason for having an option that makes this a fatal error. I am just envisaging this as a useful bit of feedback to help avoid accidental use of the wrong Unicode code point. Carrying on and outputting the character is helpful because the user can then look at the typeset output and decide whether or not they wanted to use that code point.

**Comment by rbjones** [comment]
Presumably we are not worried about the performance hit (the only remaining reason to make it optional)?

**Comment by rbjones** [comment]
I suppose people working like I am at the moment, using utf8, lualatex and the minimal keyword file, might well find the number of warnings excessive.

**Comment by RobArthan** [comment]
By all means, let's make the check optional if that's convenient for lualatex users.

**Comment by rbjones** [comment]
I've done a compact report which comes out as a single message, without duplicates, listing all the undeclared unicodes, and because that's pretty concise I didn't put in a flag to suppress it.
It displays both the character and the code (in hex), and the character might come out strange if your font doesn't cover it.  It won't come out if sieve aborts.
